
services:
<<<<<<< HEAD
#  frontend:
#    build: ./frontend
#    container_name: ft_transcendence_frontend
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
#    networks:
#      - pong-network
#
=======
  nginx:
    image: nginx:alpine
    container_name: ft_transcendence_nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
      - frontend
      - realtime
      - auth-service

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - pong-network

  frontend:
    build: ./frontend
    container_name: ft_transcendence_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - pong-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 10

>>>>>>> develop
  backend:
    build: ./backend
    container_name: ft_transcendence_backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./data:/data
    networks:
      - pong-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 5s
      retries: 10

<<<<<<< HEAD
#  realtime:
#    build: ./realtime
#    container_name: ft_transcendence_realtime
#    ports:
#      - "8081:8081"
#    volumes:
#      - ./realtime:/app
#      - /app/node_modules
#    networks:
#      - pong-network
#
#  auth-service:
#    build: ./auth-service
#    container_name: ft_transcendence_auth
#    ports:
#      - "8082:8082"
#    volumes:
#      - ./auth-service:/app
#      - /app/node_modules
#    networks:
#      - pong-network
=======
  realtime:
    build: ./realtime
    container_name: ft_transcendence_realtime
    ports:
      - "8081:8081"
    volumes:
      - ./realtime:/app
      - /app/node_modules
    networks:
      - pong-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 10s
      timeout: 5s
      retries: 10

  auth-service:
    build: ./auth-service
    container_name: ft_transcendence_auth
    ports:
      - "8082:8082"
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    networks:
      - pong-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/api/auth/health"]
      interval: 10s
      timeout: 5s
      retries: 10
>>>>>>> develop

networks:
  pong-network:
    driver: bridge
