
global:
  scrape_interval: 15s

scrape_configs:
  # monitor Prometheus itself
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  #frontend
  - job_name: 'frontend'
    static_configs:
    - targets: ['frontend:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
  #backend
  - job_name: 'backend'
    static_configs:
    - targets: ['backend:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
  #auth-service
  - job_name: 'auth-service'
    static_configs:
    - targets: ['auth-service:8082']
    metrics_path: '/metrics'
    scrape_interval: 30s
  #realtime
  - job_name: 'realtime'
    static_configs:
    - targets: ['realtime:8081']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
    - targets: ['nginx-exporter:9113']
    metrics_path: '/metrics'
    scrape_interval: 30s
  - job_name: 'grafana'
    static_configs:
    - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s